// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/network.dart';
import 'api/protocol.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1775480797;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_yl_chat',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<MessageEnvelope> crateApiProtocolPeerManagerAddReceptionHandlerFor({
    required PeerManager that,
    required String peerId,
  });

  Future<String> crateApiProtocolPeerManagerConnectPeer({
    required PeerManager that,
    required String peerIp,
    required String senderId,
    required int port,
  });

  Stream<String> crateApiProtocolPeerManagerCreatePeerListener({
    required PeerManager that,
    required String senderId,
  });

  Future<PeerManager> crateApiProtocolPeerManagerDefault();

  Future<void> crateApiProtocolPeerManagerDisconnectPeer({
    required PeerManager that,
    required String peerId,
  });

  Future<PeerManager> crateApiProtocolPeerManagerNew();

  Future<String> crateApiProtocolPeerManagerSendChatMessage({
    required PeerManager that,
    required String peerId,
    required String content,
  });

  Future<void> crateApiProtocolPeerManagerSendMessageWith({
    required PeerManager that,
    required String peerId,
    required String content,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiNetworkRegisterBonjourService();

  Future<List<String>> crateApiNetworkScanLanPeers();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PeerManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PeerManager;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PeerManagerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<MessageEnvelope> crateApiProtocolPeerManagerAddReceptionHandlerFor({
    required PeerManager that,
    required String peerId,
  }) {
    final sink = RustStreamSink<MessageEnvelope>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
              that,
              serializer,
            );
            sse_encode_StreamSink_message_envelope_Sse(sink, serializer);
            sse_encode_String(peerId, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta:
              kCrateApiProtocolPeerManagerAddReceptionHandlerForConstMeta,
          argValues: [that, sink, peerId],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiProtocolPeerManagerAddReceptionHandlerForConstMeta =>
      const TaskConstMeta(
        debugName: "PeerManager_add_reception_handler_for",
        argNames: ["that", "sink", "peerId"],
      );

  @override
  Future<String> crateApiProtocolPeerManagerConnectPeer({
    required PeerManager that,
    required String peerIp,
    required String senderId,
    required int port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
            that,
            serializer,
          );
          sse_encode_String(peerIp, serializer);
          sse_encode_String(senderId, serializer);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolPeerManagerConnectPeerConstMeta,
        argValues: [that, peerIp, senderId, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerConnectPeerConstMeta =>
      const TaskConstMeta(
        debugName: "PeerManager_connect_peer",
        argNames: ["that", "peerIp", "senderId", "port"],
      );

  @override
  Stream<String> crateApiProtocolPeerManagerCreatePeerListener({
    required PeerManager that,
    required String senderId,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
              that,
              serializer,
            );
            sse_encode_StreamSink_String_Sse(sink, serializer);
            sse_encode_String(senderId, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiProtocolPeerManagerCreatePeerListenerConstMeta,
          argValues: [that, sink, senderId],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerCreatePeerListenerConstMeta =>
      const TaskConstMeta(
        debugName: "PeerManager_create_peer_listener",
        argNames: ["that", "sink", "senderId"],
      );

  @override
  Future<PeerManager> crateApiProtocolPeerManagerDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolPeerManagerDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerDefaultConstMeta =>
      const TaskConstMeta(debugName: "PeerManager_default", argNames: []);

  @override
  Future<void> crateApiProtocolPeerManagerDisconnectPeer({
    required PeerManager that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolPeerManagerDisconnectPeerConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerDisconnectPeerConstMeta =>
      const TaskConstMeta(
        debugName: "PeerManager_disconnect_peer",
        argNames: ["that", "peerId"],
      );

  @override
  Future<PeerManager> crateApiProtocolPeerManagerNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolPeerManagerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerNewConstMeta =>
      const TaskConstMeta(debugName: "PeerManager_new", argNames: []);

  @override
  Future<String> crateApiProtocolPeerManagerSendChatMessage({
    required PeerManager that,
    required String peerId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolPeerManagerSendChatMessageConstMeta,
        argValues: [that, peerId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerSendChatMessageConstMeta =>
      const TaskConstMeta(
        debugName: "PeerManager_send_chat_message",
        argNames: ["that", "peerId", "content"],
      );

  @override
  Future<void> crateApiProtocolPeerManagerSendMessageWith({
    required PeerManager that,
    required String peerId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolPeerManagerSendMessageWithConstMeta,
        argValues: [that, peerId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolPeerManagerSendMessageWithConstMeta =>
      const TaskConstMeta(
        debugName: "PeerManager_send_message_with",
        argNames: ["that", "peerId", "content"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiNetworkRegisterBonjourService() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkRegisterBonjourServiceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRegisterBonjourServiceConstMeta =>
      const TaskConstMeta(debugName: "register_bonjour_service", argNames: []);

  @override
  Future<List<String>> crateApiNetworkScanLanPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkScanLanPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkScanLanPeersConstMeta =>
      const TaskConstMeta(debugName: "scan_lan_peers", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PeerManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PeerManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  PeerManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PeerManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PeerManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PeerManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MessageEnvelope> dco_decode_StreamSink_message_envelope_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageEnvelope dco_decode_message_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MessageEnvelope(
      version: dco_decode_u_8(arr[0]),
      msgId: dco_decode_String(arr[1]),
      senderId: dco_decode_String(arr[2]),
      timestamp: dco_decode_i_64(arr[3]),
      payload: dco_decode_message_payload(arr[4]),
    );
  }

  @protected
  MessagePayload dco_decode_message_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MessagePayload_Handshake(
          clientVersion: dco_decode_u_8(raw[1]),
          publicKey: dco_decode_opt_String(raw[2]),
          peerId: dco_decode_String(raw[3]),
        );
      case 1:
        return MessagePayload_ChatMessage(content: dco_decode_String(raw[1]));
      case 2:
        return MessagePayload_Ack(
          targetMsgId: dco_decode_String(raw[1]),
          status: dco_decode_String(raw[2]),
        );
      case 3:
        return MessagePayload_Ping();
      case 4:
        return MessagePayload_Pong();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  PeerManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PeerManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PeerManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PeerManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MessageEnvelope> sse_decode_StreamSink_message_envelope_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageEnvelope sse_decode_message_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_8(deserializer);
    var var_msgId = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_payload = sse_decode_message_payload(deserializer);
    return MessageEnvelope(
      version: var_version,
      msgId: var_msgId,
      senderId: var_senderId,
      timestamp: var_timestamp,
      payload: var_payload,
    );
  }

  @protected
  MessagePayload sse_decode_message_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_clientVersion = sse_decode_u_8(deserializer);
        var var_publicKey = sse_decode_opt_String(deserializer);
        var var_peerId = sse_decode_String(deserializer);
        return MessagePayload_Handshake(
          clientVersion: var_clientVersion,
          publicKey: var_publicKey,
          peerId: var_peerId,
        );
      case 1:
        var var_content = sse_decode_String(deserializer);
        return MessagePayload_ChatMessage(content: var_content);
      case 2:
        var var_targetMsgId = sse_decode_String(deserializer);
        var var_status = sse_decode_String(deserializer);
        return MessagePayload_Ack(
          targetMsgId: var_targetMsgId,
          status: var_status,
        );
      case 3:
        return MessagePayload_Ping();
      case 4:
        return MessagePayload_Pong();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    PeerManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    PeerManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerManager(
    PeerManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PeerManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_message_envelope_Sse(
    RustStreamSink<MessageEnvelope> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_envelope,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_envelope(
    MessageEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.version, serializer);
    sse_encode_String(self.msgId, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_message_payload(self.payload, serializer);
  }

  @protected
  void sse_encode_message_payload(
    MessagePayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MessagePayload_Handshake(
        clientVersion: final clientVersion,
        publicKey: final publicKey,
        peerId: final peerId,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_8(clientVersion, serializer);
        sse_encode_opt_String(publicKey, serializer);
        sse_encode_String(peerId, serializer);
      case MessagePayload_ChatMessage(content: final content):
        sse_encode_i_32(1, serializer);
        sse_encode_String(content, serializer);
      case MessagePayload_Ack(
        targetMsgId: final targetMsgId,
        status: final status,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(targetMsgId, serializer);
        sse_encode_String(status, serializer);
      case MessagePayload_Ping():
        sse_encode_i_32(3, serializer);
      case MessagePayload_Pong():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class PeerManagerImpl extends RustOpaque implements PeerManager {
  // Not to be used by end users
  PeerManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PeerManagerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PeerManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PeerManager,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PeerManagerPtr,
  );

  Stream<MessageEnvelope> addReceptionHandlerFor({required String peerId}) =>
      RustLib.instance.api.crateApiProtocolPeerManagerAddReceptionHandlerFor(
        that: this,
        peerId: peerId,
      );

  /// Connect to a remote peer and return its peer_id
  Future<String> connectPeer({
    required String peerIp,
    required String senderId,
    required int port,
  }) => RustLib.instance.api.crateApiProtocolPeerManagerConnectPeer(
    that: this,
    peerIp: peerIp,
    senderId: senderId,
    port: port,
  );

  Stream<String> createPeerListener({required String senderId}) =>
      RustLib.instance.api.crateApiProtocolPeerManagerCreatePeerListener(
        that: this,
        senderId: senderId,
      );

  /// Close session by peer_id
  Future<void> disconnectPeer({required String peerId}) => RustLib.instance.api
      .crateApiProtocolPeerManagerDisconnectPeer(that: this, peerId: peerId);

  /// Send chat message by peer_id
  Future<String> sendChatMessage({
    required String peerId,
    required String content,
  }) => RustLib.instance.api.crateApiProtocolPeerManagerSendChatMessage(
    that: this,
    peerId: peerId,
    content: content,
  );

  Future<void> sendMessageWith({
    required String peerId,
    required String content,
  }) => RustLib.instance.api.crateApiProtocolPeerManagerSendMessageWith(
    that: this,
    peerId: peerId,
    content: content,
  );
}
