// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/discovery.dart';
import 'api/discovery/bridge.dart';
import 'api/protocol.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1690476631;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_yl_chat',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiProtocolLocalStorageAppendMessage({
    required LocalStorage that,
    required String peerMac,
    required PersistentMessage msg,
  });

  Future<List<PeerRecord>> crateApiProtocolLocalStorageGetAllPeers({
    required LocalStorage that,
  });

  Future<List<PersistentMessage>>
  crateApiProtocolLocalStorageGetMessagesForPeer({
    required LocalStorage that,
    required String peerMac,
  });

  Future<PeerRecord?> crateApiProtocolLocalStorageGetPeer({
    required LocalStorage that,
    required String mac,
  });

  Future<List<PersistentMessage>>
  crateApiProtocolLocalStorageGetPendingMessages({
    required LocalStorage that,
    required String peerMac,
  });

  Future<bool> crateApiProtocolLocalStorageMarkAcked({
    required LocalStorage that,
    required String peerMac,
    required String targetMsgId,
  });

  Future<LocalStorage> crateApiProtocolLocalStorageOpen({
    required PathBuf dbPath,
  });

  Future<void> crateApiProtocolLocalStorageUpsertPeer({
    required LocalStorage that,
    required PeerRecord record,
  });

  String crateApiProtocolNetworkEngineAutoAccessorGetSelfMac({
    required NetworkEngine that,
  });

  void crateApiProtocolNetworkEngineAutoAccessorSetSelfMac({
    required NetworkEngine that,
    required String selfMac,
  });

  Future<void> crateApiProtocolNetworkEngineFlushOutbox({
    required NetworkEngine that,
    required String peerMac,
  });

  Future<List<PersistentMessage>> crateApiProtocolNetworkEngineGetMessages({
    required NetworkEngine that,
    required String peerMac,
  });

  Future<List<PeerRecord>> crateApiProtocolNetworkEngineGetPeers({
    required NetworkEngine that,
  });

  Future<NetworkEngine> crateApiProtocolNetworkEngineNew({
    required String selfMac,
    required String dbPathStr,
  });

  Stream<String> crateApiProtocolNetworkEngineRegisterNotifySink({
    required NetworkEngine that,
  });

  Future<void> crateApiProtocolNetworkEngineRunScanAndFlushCycle({
    required NetworkEngine that,
  });

  Future<void> crateApiProtocolNetworkEngineSendMessage({
    required NetworkEngine that,
    required String recipientMac,
    required String content,
  });

  Stream<String> crateApiProtocolNetworkEngineStartListener({
    required NetworkEngine that,
    required int port,
  });

  Future<void> crateApiProtocolNetworkEngineUpsertPeer({
    required NetworkEngine that,
    required PeerRecord record,
  });

  Future<PlatformInt64> crateApiProtocolChronoNowTimestamp();

  Future<String> crateApiDiscoveryGetDeviceIdentifier();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiProtocolMessageStatusAsStr({
    required MessageStatus that,
  });

  Future<MessageStatus> crateApiProtocolMessageStatusFromStr({
    required String s,
  });

  Future<void> crateApiDiscoveryRegisterBonjourService({
    required String macAddress,
  });

  Future<void> crateApiDiscoveryBridgeScanAndFlush({
    required NetworkEngine engine,
  });

  Future<List<PeerInfo>> crateApiDiscoveryScanLanPeers();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocalStorage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocalStorage;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LocalStoragePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NetworkEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NetworkEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NetworkEnginePtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_PathBuf;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_PathBuf;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PathBufPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiProtocolLocalStorageAppendMessage({
    required LocalStorage that,
    required String peerMac,
    required PersistentMessage msg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          sse_encode_String(peerMac, serializer);
          sse_encode_box_autoadd_persistent_message(msg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageAppendMessageConstMeta,
        argValues: [that, peerMac, msg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageAppendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_append_message",
        argNames: ["that", "peerMac", "msg"],
      );

  @override
  Future<List<PeerRecord>> crateApiProtocolLocalStorageGetAllPeers({
    required LocalStorage that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageGetAllPeersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageGetAllPeersConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_get_all_peers",
        argNames: ["that"],
      );

  @override
  Future<List<PersistentMessage>>
  crateApiProtocolLocalStorageGetMessagesForPeer({
    required LocalStorage that,
    required String peerMac,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          sse_encode_String(peerMac, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_persistent_message,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageGetMessagesForPeerConstMeta,
        argValues: [that, peerMac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageGetMessagesForPeerConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_get_messages_for_peer",
        argNames: ["that", "peerMac"],
      );

  @override
  Future<PeerRecord?> crateApiProtocolLocalStorageGetPeer({
    required LocalStorage that,
    required String mac,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          sse_encode_String(mac, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_peer_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageGetPeerConstMeta,
        argValues: [that, mac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageGetPeerConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_get_peer",
        argNames: ["that", "mac"],
      );

  @override
  Future<List<PersistentMessage>>
  crateApiProtocolLocalStorageGetPendingMessages({
    required LocalStorage that,
    required String peerMac,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          sse_encode_String(peerMac, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_persistent_message,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageGetPendingMessagesConstMeta,
        argValues: [that, peerMac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageGetPendingMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_get_pending_messages",
        argNames: ["that", "peerMac"],
      );

  @override
  Future<bool> crateApiProtocolLocalStorageMarkAcked({
    required LocalStorage that,
    required String peerMac,
    required String targetMsgId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          sse_encode_String(peerMac, serializer);
          sse_encode_String(targetMsgId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageMarkAckedConstMeta,
        argValues: [that, peerMac, targetMsgId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageMarkAckedConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_mark_acked",
        argNames: ["that", "peerMac", "targetMsgId"],
      );

  @override
  Future<LocalStorage> crateApiProtocolLocalStorageOpen({
    required PathBuf dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
            dbPath,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolLocalStorageOpenConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageOpenConstMeta =>
      const TaskConstMeta(debugName: "LocalStorage_open", argNames: ["dbPath"]);

  @override
  Future<void> crateApiProtocolLocalStorageUpsertPeer({
    required LocalStorage that,
    required PeerRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
            that,
            serializer,
          );
          sse_encode_box_autoadd_peer_record(record, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolLocalStorageUpsertPeerConstMeta,
        argValues: [that, record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolLocalStorageUpsertPeerConstMeta =>
      const TaskConstMeta(
        debugName: "LocalStorage_upsert_peer",
        argNames: ["that", "record"],
      );

  @override
  String crateApiProtocolNetworkEngineAutoAccessorGetSelfMac({
    required NetworkEngine that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiProtocolNetworkEngineAutoAccessorGetSelfMacConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiProtocolNetworkEngineAutoAccessorGetSelfMacConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_auto_accessor_get_self_mac",
        argNames: ["that"],
      );

  @override
  void crateApiProtocolNetworkEngineAutoAccessorSetSelfMac({
    required NetworkEngine that,
    required String selfMac,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          sse_encode_String(selfMac, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiProtocolNetworkEngineAutoAccessorSetSelfMacConstMeta,
        argValues: [that, selfMac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiProtocolNetworkEngineAutoAccessorSetSelfMacConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_auto_accessor_set_self_mac",
        argNames: ["that", "selfMac"],
      );

  @override
  Future<void> crateApiProtocolNetworkEngineFlushOutbox({
    required NetworkEngine that,
    required String peerMac,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          sse_encode_String(peerMac, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolNetworkEngineFlushOutboxConstMeta,
        argValues: [that, peerMac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineFlushOutboxConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_flush_outbox",
        argNames: ["that", "peerMac"],
      );

  @override
  Future<List<PersistentMessage>> crateApiProtocolNetworkEngineGetMessages({
    required NetworkEngine that,
    required String peerMac,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          sse_encode_String(peerMac, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_persistent_message,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolNetworkEngineGetMessagesConstMeta,
        argValues: [that, peerMac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineGetMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_get_messages",
        argNames: ["that", "peerMac"],
      );

  @override
  Future<List<PeerRecord>> crateApiProtocolNetworkEngineGetPeers({
    required NetworkEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolNetworkEngineGetPeersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineGetPeersConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_get_peers",
        argNames: ["that"],
      );

  @override
  Future<NetworkEngine> crateApiProtocolNetworkEngineNew({
    required String selfMac,
    required String dbPathStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(selfMac, serializer);
          sse_encode_String(dbPathStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolNetworkEngineNewConstMeta,
        argValues: [selfMac, dbPathStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineNewConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_new",
        argNames: ["selfMac", "dbPathStr"],
      );

  @override
  Stream<String> crateApiProtocolNetworkEngineRegisterNotifySink({
    required NetworkEngine that,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
              that,
              serializer,
            );
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiProtocolNetworkEngineRegisterNotifySinkConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineRegisterNotifySinkConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_register_notify_sink",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiProtocolNetworkEngineRunScanAndFlushCycle({
    required NetworkEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolNetworkEngineRunScanAndFlushCycleConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiProtocolNetworkEngineRunScanAndFlushCycleConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_run_scan_and_flush_cycle",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiProtocolNetworkEngineSendMessage({
    required NetworkEngine that,
    required String recipientMac,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          sse_encode_String(recipientMac, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProtocolNetworkEngineSendMessageConstMeta,
        argValues: [that, recipientMac, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_send_message",
        argNames: ["that", "recipientMac", "content"],
      );

  @override
  Stream<String> crateApiProtocolNetworkEngineStartListener({
    required NetworkEngine that,
    required int port,
  }) {
    final notifySink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
              that,
              serializer,
            );
            sse_encode_u_16(port, serializer);
            sse_encode_StreamSink_String_Sse(notifySink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiProtocolNetworkEngineStartListenerConstMeta,
          argValues: [that, port, notifySink],
          apiImpl: this,
        ),
      ),
    );
    return notifySink.stream;
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineStartListenerConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_start_listener",
        argNames: ["that", "port", "notifySink"],
      );

  @override
  Future<void> crateApiProtocolNetworkEngineUpsertPeer({
    required NetworkEngine that,
    required PeerRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            that,
            serializer,
          );
          sse_encode_box_autoadd_peer_record(record, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolNetworkEngineUpsertPeerConstMeta,
        argValues: [that, record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolNetworkEngineUpsertPeerConstMeta =>
      const TaskConstMeta(
        debugName: "NetworkEngine_upsert_peer",
        argNames: ["that", "record"],
      );

  @override
  Future<PlatformInt64> crateApiProtocolChronoNowTimestamp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolChronoNowTimestampConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolChronoNowTimestampConstMeta =>
      const TaskConstMeta(debugName: "chrono_now_timestamp", argNames: []);

  @override
  Future<String> crateApiDiscoveryGetDeviceIdentifier() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiscoveryGetDeviceIdentifierConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryGetDeviceIdentifierConstMeta =>
      const TaskConstMeta(debugName: "get_device_identifier", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiProtocolMessageStatusAsStr({
    required MessageStatus that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_message_status(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolMessageStatusAsStrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolMessageStatusAsStrConstMeta =>
      const TaskConstMeta(
        debugName: "message_status_as_str",
        argNames: ["that"],
      );

  @override
  Future<MessageStatus> crateApiProtocolMessageStatusFromStr({
    required String s,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProtocolMessageStatusFromStrConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProtocolMessageStatusFromStrConstMeta =>
      const TaskConstMeta(
        debugName: "message_status_from_str",
        argNames: ["s"],
      );

  @override
  Future<void> crateApiDiscoveryRegisterBonjourService({
    required String macAddress,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(macAddress, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiscoveryRegisterBonjourServiceConstMeta,
        argValues: [macAddress],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryRegisterBonjourServiceConstMeta =>
      const TaskConstMeta(
        debugName: "register_bonjour_service",
        argNames: ["macAddress"],
      );

  @override
  Future<void> crateApiDiscoveryBridgeScanAndFlush({
    required NetworkEngine engine,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
            engine,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDiscoveryBridgeScanAndFlushConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryBridgeScanAndFlushConstMeta =>
      const TaskConstMeta(debugName: "scan_and_flush", argNames: ["engine"]);

  @override
  Future<List<PeerInfo>> crateApiDiscoveryScanLanPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiscoveryScanLanPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryScanLanPeersConstMeta =>
      const TaskConstMeta(debugName: "scan_lan_peers", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LocalStorage => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LocalStorage => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NetworkEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NetworkEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PathBuf => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PathBuf => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  LocalStorage
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocalStorageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NetworkEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PathBuf
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PathBufImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NetworkEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocalStorage
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocalStorageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NetworkEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LocalStorage
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocalStorageImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NetworkEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PathBuf
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PathBufImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PeerRecord dco_decode_box_autoadd_peer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_peer_record(raw);
  }

  @protected
  PersistentMessage dco_decode_box_autoadd_persistent_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_persistent_message(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<PeerInfo> dco_decode_list_peer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_info).toList();
  }

  @protected
  List<PeerRecord> dco_decode_list_peer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_record).toList();
  }

  @protected
  List<PersistentMessage> dco_decode_list_persistent_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_persistent_message).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageStatus dco_decode_message_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageStatus.values[raw as int];
  }

  @protected
  PeerRecord? dco_decode_opt_box_autoadd_peer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_peer_record(raw);
  }

  @protected
  PeerInfo dco_decode_peer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PeerInfo(
      macAddress: dco_decode_String(arr[0]),
      ip: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
    );
  }

  @protected
  PeerRecord dco_decode_peer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PeerRecord(
      macAddress: dco_decode_String(arr[0]),
      lastKnownIp: dco_decode_String(arr[1]),
      port: dco_decode_u_16(arr[2]),
      deviceName: dco_decode_String(arr[3]),
      lastSeen: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  PersistentMessage dco_decode_persistent_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PersistentMessage(
      msgId: dco_decode_String(arr[0]),
      peerMac: dco_decode_String(arr[1]),
      isOutgoing: dco_decode_bool(arr[2]),
      content: dco_decode_String(arr[3]),
      timestamp: dco_decode_i_64(arr[4]),
      status: dco_decode_message_status(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  LocalStorage
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocalStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NetworkEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PathBuf
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PathBufImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NetworkEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocalStorage
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocalStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NetworkEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LocalStorage
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LocalStorageImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NetworkEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NetworkEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PathBuf
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PathBufImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PeerRecord sse_decode_box_autoadd_peer_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_peer_record(deserializer));
  }

  @protected
  PersistentMessage sse_decode_box_autoadd_persistent_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_persistent_message(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<PeerInfo> sse_decode_list_peer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerRecord> sse_decode_list_peer_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<PersistentMessage> sse_decode_list_persistent_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PersistentMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_persistent_message(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageStatus sse_decode_message_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageStatus.values[inner];
  }

  @protected
  PeerRecord? sse_decode_opt_box_autoadd_peer_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_peer_record(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerInfo sse_decode_peer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_macAddress = sse_decode_String(deserializer);
    var var_ip = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    return PeerInfo(
      macAddress: var_macAddress,
      ip: var_ip,
      deviceName: var_deviceName,
    );
  }

  @protected
  PeerRecord sse_decode_peer_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_macAddress = sse_decode_String(deserializer);
    var var_lastKnownIp = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_lastSeen = sse_decode_i_64(deserializer);
    return PeerRecord(
      macAddress: var_macAddress,
      lastKnownIp: var_lastKnownIp,
      port: var_port,
      deviceName: var_deviceName,
      lastSeen: var_lastSeen,
    );
  }

  @protected
  PersistentMessage sse_decode_persistent_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msgId = sse_decode_String(deserializer);
    var var_peerMac = sse_decode_String(deserializer);
    var var_isOutgoing = sse_decode_bool(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_status = sse_decode_message_status(deserializer);
    return PersistentMessage(
      msgId: var_msgId,
      peerMac: var_peerMac,
      isOutgoing: var_isOutgoing,
      content: var_content,
      timestamp: var_timestamp,
      status: var_status,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    LocalStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocalStorageImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    NetworkEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
    PathBuf self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PathBufImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    NetworkEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    LocalStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocalStorageImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    NetworkEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalStorage(
    LocalStorage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LocalStorageImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNetworkEngine(
    NetworkEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NetworkEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPathBuf(
    PathBuf self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PathBufImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_peer_record(
    PeerRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_peer_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_persistent_message(
    PersistentMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_persistent_message(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_peer_info(
    List<PeerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_record(
    List<PeerRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_persistent_message(
    List<PersistentMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_persistent_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_status(MessageStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_peer_record(
    PeerRecord? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_peer_record(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_info(PeerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.macAddress, serializer);
    sse_encode_String(self.ip, serializer);
    sse_encode_String(self.deviceName, serializer);
  }

  @protected
  void sse_encode_peer_record(PeerRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.macAddress, serializer);
    sse_encode_String(self.lastKnownIp, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_i_64(self.lastSeen, serializer);
  }

  @protected
  void sse_encode_persistent_message(
    PersistentMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.msgId, serializer);
    sse_encode_String(self.peerMac, serializer);
    sse_encode_bool(self.isOutgoing, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_message_status(self.status, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class LocalStorageImpl extends RustOpaque implements LocalStorage {
  // Not to be used by end users
  LocalStorageImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LocalStorageImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LocalStorage,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocalStorage,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LocalStoragePtr,
  );

  Future<void> appendMessage({
    required String peerMac,
    required PersistentMessage msg,
  }) => RustLib.instance.api.crateApiProtocolLocalStorageAppendMessage(
    that: this,
    peerMac: peerMac,
    msg: msg,
  );

  Future<List<PeerRecord>> getAllPeers() =>
      RustLib.instance.api.crateApiProtocolLocalStorageGetAllPeers(that: this);

  Future<List<PersistentMessage>> getMessagesForPeer({
    required String peerMac,
  }) => RustLib.instance.api.crateApiProtocolLocalStorageGetMessagesForPeer(
    that: this,
    peerMac: peerMac,
  );

  Future<PeerRecord?> getPeer({required String mac}) => RustLib.instance.api
      .crateApiProtocolLocalStorageGetPeer(that: this, mac: mac);

  Future<List<PersistentMessage>> getPendingMessages({
    required String peerMac,
  }) => RustLib.instance.api.crateApiProtocolLocalStorageGetPendingMessages(
    that: this,
    peerMac: peerMac,
  );

  Future<bool> markAcked({
    required String peerMac,
    required String targetMsgId,
  }) => RustLib.instance.api.crateApiProtocolLocalStorageMarkAcked(
    that: this,
    peerMac: peerMac,
    targetMsgId: targetMsgId,
  );

  Future<void> upsertPeer({required PeerRecord record}) => RustLib.instance.api
      .crateApiProtocolLocalStorageUpsertPeer(that: this, record: record);
}

@sealed
class NetworkEngineImpl extends RustOpaque implements NetworkEngine {
  // Not to be used by end users
  NetworkEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NetworkEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NetworkEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NetworkEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NetworkEnginePtr,
  );

  String get selfMac => RustLib.instance.api
      .crateApiProtocolNetworkEngineAutoAccessorGetSelfMac(that: this);

  set selfMac(String selfMac) =>
      RustLib.instance.api.crateApiProtocolNetworkEngineAutoAccessorSetSelfMac(
        that: this,
        selfMac: selfMac,
      );

  Future<void> flushOutbox({required String peerMac}) => RustLib.instance.api
      .crateApiProtocolNetworkEngineFlushOutbox(that: this, peerMac: peerMac);

  /// Exposes chat retrieval directly to Dart
  Future<List<PersistentMessage>> getMessages({required String peerMac}) =>
      RustLib.instance.api.crateApiProtocolNetworkEngineGetMessages(
        that: this,
        peerMac: peerMac,
      );

  /// Exposes peer fetching directly to Dart
  Future<List<PeerRecord>> getPeers() =>
      RustLib.instance.api.crateApiProtocolNetworkEngineGetPeers(that: this);

  Stream<String> registerNotifySink() => RustLib.instance.api
      .crateApiProtocolNetworkEngineRegisterNotifySink(that: this);

  Future<void> runScanAndFlushCycle() => RustLib.instance.api
      .crateApiProtocolNetworkEngineRunScanAndFlushCycle(that: this);

  Future<void> sendMessage({
    required String recipientMac,
    required String content,
  }) => RustLib.instance.api.crateApiProtocolNetworkEngineSendMessage(
    that: this,
    recipientMac: recipientMac,
    content: content,
  );

  Stream<String> startListener({required int port}) => RustLib.instance.api
      .crateApiProtocolNetworkEngineStartListener(that: this, port: port);

  /// Exposes peer insertion directly to Dart
  Future<void> upsertPeer({required PeerRecord record}) => RustLib.instance.api
      .crateApiProtocolNetworkEngineUpsertPeer(that: this, record: record);
}

@sealed
class PathBufImpl extends RustOpaque implements PathBuf {
  // Not to be used by end users
  PathBufImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PathBufImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PathBuf,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PathBuf,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PathBufPtr,
  );
}
