// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

// These functions are ignored because they are not marked as `pub`: `init_db_tables`, `rebuild_schema`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LocalStorage`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `append_message`, `clear_file_transfer_trackers`, `get_acked_outbound_chunks`, `get_all_peers`, `get_file_transfer`, `get_messages_for_peer`, `get_peer`, `get_pending_messages`, `get_pending_outbound_transfers`, `has_message`, `insert_file_transfer`, `mark_acked`, `mark_transfer_completed`, `open`, `record_chunk_received`, `record_outbound_chunk_ack`, `set_peer_online_status`, `upsert_peer`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalStorageHandle>>
abstract class LocalStorageHandle implements RustOpaqueInterface {
  Future<void> appendMessage({
    required String peerMac,
    required PersistentMessage msg,
  });

  Future<StorageRepositoryHandle> asStorageRepository();

  Future<void> clearFileTransferTrackers({required String transferId});

  Future<Uint32List> getAckedOutboundChunks({required String transferId});

  Future<List<PeerRecord>> getAllPeers();

  Future<FileTransferRecord?> getFileTransfer({required String transferId});

  Future<List<PersistentMessage>> getMessagesForPeer({required String peerMac});

  Future<PeerRecord?> getPeer({required String mac});

  Future<List<PersistentMessage>> getPendingMessages({required String peerMac});

  Future<List<FileTransferRecord>> getPendingOutboundTransfers({
    required String peerMac,
  });

  Future<bool> hasMessage({required String msgId});

  Future<void> insertFileTransfer({required FileTransferRecord record});

  Future<bool> markAcked({
    required String peerMac,
    required String targetMsgId,
  });

  Future<void> markTransferCompleted({required String transferId});

  static Future<LocalStorageHandle> open({required String dbPath}) => RustLib
      .instance
      .api
      .crateApiStorageSqliteLocalStorageHandleOpen(dbPath: dbPath);

  Future<int> recordChunkReceived({
    required String transferId,
    required int chunkIndex,
  });

  Future<void> recordOutboundChunkAck({
    required String transferId,
    required int chunkIndex,
  });

  Future<void> setPeerOnlineStatus({
    required String mac,
    required bool isOnline,
  });

  Future<void> upsertPeer({required PeerRecord record});
}
