// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../connection/traits.dart';
import '../storage/traits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

// These functions are ignored because they are not marked as `pub`: `clone_service`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DefaultMessagingService`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `flush_outbox`, `send_message`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DefaultMessagingServiceHandle>>
abstract class DefaultMessagingServiceHandle implements RustOpaqueInterface {
  Future<MessagingServiceHandle> asMessagingService();

  Future<void> flushOutbox({required String peerMac});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DefaultMessagingServiceHandle> newInstance({
    required String selfMac,
    required StorageRepositoryHandle storageHandle,
    required ConnectionManagerHandle connManagerHandle,
  }) => RustLib.instance.api
      .crateApiMessagingServiceDefaultMessagingServiceHandleNew(
        selfMac: selfMac,
        storageHandle: storageHandle,
        connManagerHandle: connManagerHandle,
      );

  Future<void> sendMessage({
    required String recipientMac,
    required String content,
  });
}
