// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `flush_outbox`, `send_message`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessagingServiceHandle>>
abstract class MessagingServiceHandle implements RustOpaqueInterface {
  Future<void> flushOutbox({required String peerMac});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MessagingServiceHandle> newInstance({
    required ArcMessagingService inner,
  }) => RustLib.instance.api.crateApiMessagingTraitsMessagingServiceHandleNew(
    inner: inner,
  );

  Future<void> sendMessage({
    required String recipientMac,
    required String content,
  });
}
