// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../connection/traits.dart';
import '../storage/traits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DefaultFileTransferService`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `dispatch_file_chunks`, `resume_pending_file_transfers`, `send_file`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DefaultFileTransferServiceHandle>>
abstract class DefaultFileTransferServiceHandle implements RustOpaqueInterface {
  Future<FileTransferServiceHandle> asFileTransferService();

  Future<void> dispatchFileChunks({
    required String recipientMac,
    required String transferId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DefaultFileTransferServiceHandle> newInstance({
    required String selfMac,
    required StorageRepositoryHandle storageHandle,
    required ConnectionManagerHandle connManagerHandle,
  }) => RustLib.instance.api
      .crateApiFileTransferServiceDefaultFileTransferServiceHandleNew(
        selfMac: selfMac,
        storageHandle: storageHandle,
        connManagerHandle: connManagerHandle,
      );

  Future<void> resumePendingFileTransfers({required String peerMac});

  Future<String> sendFile({
    required String recipientMac,
    required String filePathStr,
  });
}
