// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `dispatch_file_chunks`, `resume_pending_file_transfers`, `send_file`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FileTransferServiceHandle>>
abstract class FileTransferServiceHandle implements RustOpaqueInterface {
  Future<void> dispatchFileChunks({
    required String recipientMac,
    required String transferId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FileTransferServiceHandle> newInstance({
    required ArcFileTransferService inner,
  }) => RustLib.instance.api
      .crateApiFileTransferTraitsFileTransferServiceHandleNew(inner: inner);

  Future<void> resumePendingFileTransfers({required String peerMac});

  Future<String> sendFile({
    required String recipientMac,
    required String filePathStr,
  });
}
