// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'file_transfer/traits.dart';
import 'messaging/traits.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage/traits.dart';

// These functions are ignored because they are not marked as `pub`: `handle_incoming_stream`, `handle_read_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NetworkEngine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `emit_event`, `flush_outbox`, `get_messages`, `get_peers`, `new`, `register_notify_sink`, `run_scan_and_flush_cycle`, `send_file`, `send_message`, `start_listener`, `upsert_peer`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetworkEngineHandle>>
abstract class NetworkEngineHandle implements RustOpaqueInterface {
  Future<void> emitEvent({required String event});

  Future<void> flushOutbox({required String peerMac});

  Future<FileTransferServiceHandle> getFileTransferService();

  Future<List<PersistentMessage>> getMessages({required String peerMac});

  Future<MessagingServiceHandle> getMessagingService();

  Future<List<PeerRecord>> getPeers();

  Future<StorageRepositoryHandle> getStorage();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NetworkEngineHandle> newInstance({
    required String selfMac,
    required String dbPathStr,
  }) => RustLib.instance.api.crateApiEngineNetworkEngineHandleNew(
    selfMac: selfMac,
    dbPathStr: dbPathStr,
  );

  Stream<String> registerNotifySink();

  Future<void> runScanAndFlushCycle();

  Future<String> sendFile({
    required String recipientMac,
    required String filePathStr,
  });

  Future<void> sendMessage({
    required String recipientMac,
    required String content,
  });

  Stream<String> startListener({required int port});

  Future<void> upsertPeer({required PeerRecord record});
}
