// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 文件分块头信息 (Chunk Header)
class ChunkHeader {
  final String transferId;
  final String chunkUuid;
  final int chunkIndex;
  final int totalChunks;
  final BigInt offset;
  final String chunkHash;
  final String fileHash;

  const ChunkHeader({
    required this.transferId,
    required this.chunkUuid,
    required this.chunkIndex,
    required this.totalChunks,
    required this.offset,
    required this.chunkHash,
    required this.fileHash,
  });

  @override
  int get hashCode =>
      transferId.hashCode ^
      chunkUuid.hashCode ^
      chunkIndex.hashCode ^
      totalChunks.hashCode ^
      offset.hashCode ^
      chunkHash.hashCode ^
      fileHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChunkHeader &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          chunkUuid == other.chunkUuid &&
          chunkIndex == other.chunkIndex &&
          totalChunks == other.totalChunks &&
          offset == other.offset &&
          chunkHash == other.chunkHash &&
          fileHash == other.fileHash;
}

/// 数据库持久化的文件传输记录
class FileTransferRecord {
  final String transferId;
  final String peerMac;
  final FileType fileType;
  final String fileName;
  final BigInt fileSize;
  final int totalChunks;
  final int receivedChunks;
  final String fileHash;
  final String savePath;
  final bool isCompleted;
  final bool isOutgoing;

  const FileTransferRecord({
    required this.transferId,
    required this.peerMac,
    required this.fileType,
    required this.fileName,
    required this.fileSize,
    required this.totalChunks,
    required this.receivedChunks,
    required this.fileHash,
    required this.savePath,
    required this.isCompleted,
    required this.isOutgoing,
  });

  /// 获取当前传输百分比 (范围: 0 - 100)
  Future<int> progressPercentage() => RustLib.instance.api
      .crateApiModelsFileTransferRecordProgressPercentage(that: this);

  /// 获取当前传输进度的浮点值 (范围: 0.0 - 1.0)
  Future<double> progressRatio() => RustLib.instance.api
      .crateApiModelsFileTransferRecordProgressRatio(that: this);

  @override
  int get hashCode =>
      transferId.hashCode ^
      peerMac.hashCode ^
      fileType.hashCode ^
      fileName.hashCode ^
      fileSize.hashCode ^
      totalChunks.hashCode ^
      receivedChunks.hashCode ^
      fileHash.hashCode ^
      savePath.hashCode ^
      isCompleted.hashCode ^
      isOutgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileTransferRecord &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          peerMac == other.peerMac &&
          fileType == other.fileType &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          totalChunks == other.totalChunks &&
          receivedChunks == other.receivedChunks &&
          fileHash == other.fileHash &&
          savePath == other.savePath &&
          isCompleted == other.isCompleted &&
          isOutgoing == other.isOutgoing;
}

/// 文件传输类型
enum FileType {
  none,
  image,
  video,
  generic;

  Future<void> asStr() =>
      RustLib.instance.api.crateApiModelsFileTypeAsStr(that: this);

  static Future<FileType> fromStr({required String s}) =>
      RustLib.instance.api.crateApiModelsFileTypeFromStr(s: s);
}

/// 网络传输顶级信封对象 (Envelope)
class MessageEnvelope {
  final int version;
  final String msgId;
  final String senderMac;
  final MessagePayload payload;

  const MessageEnvelope({
    required this.version,
    required this.msgId,
    required this.senderMac,
    required this.payload,
  });

  @override
  int get hashCode =>
      version.hashCode ^ msgId.hashCode ^ senderMac.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageEnvelope &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          msgId == other.msgId &&
          senderMac == other.senderMac &&
          payload == other.payload;
}

@freezed
sealed class MessagePayload with _$MessagePayload {
  const MessagePayload._();

  const factory MessagePayload.handshake({required String senderMac}) =
      MessagePayload_Handshake;
  const factory MessagePayload.chatMessage({required String content}) =
      MessagePayload_ChatMessage;
  const factory MessagePayload.fileTransferInit({
    required String transferId,
    required FileType fileType,
    required String fileName,
    required BigInt fileSize,
    required int totalChunks,
    required String fileHash,
  }) = MessagePayload_FileTransferInit;
  const factory MessagePayload.fileChunk({
    required ChunkHeader header,
    required Uint8List data,
  }) = MessagePayload_FileChunk;
  const factory MessagePayload.chunkAck({
    required String transferId,
    required int chunkIndex,
  }) = MessagePayload_ChunkAck;
  const factory MessagePayload.fileCompleteAck({required String transferId}) =
      MessagePayload_FileCompleteAck;
  const factory MessagePayload.ack({required String targetMsgId}) =
      MessagePayload_Ack;
}

/// 消息发送/接收状态
enum MessageStatus {
  pending,
  acked,
  failed;

  Future<void> asStr() =>
      RustLib.instance.api.crateApiModelsMessageStatusAsStr(that: this);

  static Future<MessageStatus> fromStr({required String s}) =>
      RustLib.instance.api.crateApiModelsMessageStatusFromStr(s: s);
}

/// 节点设备记录
class PeerRecord {
  final String macAddress;
  final String lastKnownIp;
  final int port;
  final String deviceName;
  final PlatformInt64 lastSeen;
  final bool isOnline;

  const PeerRecord({
    required this.macAddress,
    required this.lastKnownIp,
    required this.port,
    required this.deviceName,
    required this.lastSeen,
    required this.isOnline,
  });

  @override
  int get hashCode =>
      macAddress.hashCode ^
      lastKnownIp.hashCode ^
      port.hashCode ^
      deviceName.hashCode ^
      lastSeen.hashCode ^
      isOnline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerRecord &&
          runtimeType == other.runtimeType &&
          macAddress == other.macAddress &&
          lastKnownIp == other.lastKnownIp &&
          port == other.port &&
          deviceName == other.deviceName &&
          lastSeen == other.lastSeen &&
          isOnline == other.isOnline;
}

/// 数据库持久化的消息记录
class PersistentMessage {
  final String msgId;
  final String peerMac;
  final bool isOutgoing;
  final String content;
  final PlatformInt64 timestamp;
  final MessageStatus status;
  final FileType fileType;
  final String? fileName;
  final BigInt? fileSize;
  final String? fileHash;
  final String? filePath;

  const PersistentMessage({
    required this.msgId,
    required this.peerMac,
    required this.isOutgoing,
    required this.content,
    required this.timestamp,
    required this.status,
    required this.fileType,
    this.fileName,
    this.fileSize,
    this.fileHash,
    this.filePath,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^
      peerMac.hashCode ^
      isOutgoing.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      status.hashCode ^
      fileType.hashCode ^
      fileName.hashCode ^
      fileSize.hashCode ^
      fileHash.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersistentMessage &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          peerMac == other.peerMac &&
          isOutgoing == other.isOutgoing &&
          content == other.content &&
          timestamp == other.timestamp &&
          status == other.status &&
          fileType == other.fileType &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          fileHash == other.fileHash &&
          filePath == other.filePath;
}
