// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_device_identifier`, `get_local_ip`, `get_or_init_daemon`

Future<void> registerBonjourService() =>
    RustLib.instance.api.crateApiNetworkRegisterBonjourService();

/// Scans the local network for peers and returns their resolved IP addresses
Future<List<String>> scanLanPeers() =>
    RustLib.instance.api.crateApiNetworkScanLanPeers();
