// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'protocol.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PeerSession`, `SessionType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_session`, `close`, `connect`, `get_session`, `handshake`, `new_incoming`, `read_envelope`, `remove_session`, `send_chat_message`, `send_envelope`, `start_reception_loop`

Future<PlatformInt64> chronoNowTimestamp() =>
    RustLib.instance.api.crateApiProtocolChronoNowTimestamp();

Future<String> getSenderId() =>
    RustLib.instance.api.crateApiProtocolGetSenderId();

Future<int> getServicePort() =>
    RustLib.instance.api.crateApiProtocolGetServicePort();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerManager>>
abstract class PeerManager implements RustOpaqueInterface {
  Stream<MessageEnvelope> addReceptionHandlerFor({required String peerId});

  /// Connect to a remote peer and return its peer_id
  Future<String> connectPeer({
    required String peerIp,
    required String senderId,
    required int port,
  });

  Stream<String> createPeerListener({required String senderId});

  static Future<PeerManager> default_() =>
      RustLib.instance.api.crateApiProtocolPeerManagerDefault();

  /// Close session by peer_id
  Future<void> disconnectPeer({required String peerId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PeerManager> newInstance() =>
      RustLib.instance.api.crateApiProtocolPeerManagerNew();

  /// Send chat message by peer_id
  Future<String> sendChatMessage({
    required String peerId,
    required String content,
  });

  Future<void> sendMessageWith({
    required String peerId,
    required String content,
  });
}

class MessageEnvelope {
  final int version;
  final String msgId;
  final String senderId;
  final PlatformInt64 timestamp;
  final MessagePayload payload;

  const MessageEnvelope({
    required this.version,
    required this.msgId,
    required this.senderId,
    required this.timestamp,
    required this.payload,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      msgId.hashCode ^
      senderId.hashCode ^
      timestamp.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageEnvelope &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          msgId == other.msgId &&
          senderId == other.senderId &&
          timestamp == other.timestamp &&
          payload == other.payload;
}

@freezed
sealed class MessagePayload with _$MessagePayload {
  const MessagePayload._();

  const factory MessagePayload.handshake({
    required int clientVersion,
    String? publicKey,
    required String peerId,
  }) = MessagePayload_Handshake;
  const factory MessagePayload.chatMessage({required String content}) =
      MessagePayload_ChatMessage;
  const factory MessagePayload.ack({
    required String targetMsgId,
    required String status,
  }) = MessagePayload_Ack;
  const factory MessagePayload.ping() = MessagePayload_Ping;
  const factory MessagePayload.pong() = MessagePayload_Pong;
}
