// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'protocol.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `chrono_now_timestamp`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerSession>>
abstract class PeerSession implements RustOpaqueInterface {
  String get peerId;

  String get peerIp;

  set peerId(String peerId);

  set peerIp(String peerIp);

  /// Close the session socket
  Future<void> close();

  /// Connect to a remote peer via IP and port
  static Future<PeerSession> connect({
    required String peerId,
    required String peerIp,
    required int port,
  }) => RustLib.instance.api.crateApiProtocolPeerSessionConnect(
    peerId: peerId,
    peerIp: peerIp,
    port: port,
  );

  /// Read the next incoming MessageEnvelope from the TCP stream
  Future<MessageEnvelope> readEnvelope();

  /// Send a Chat Message envelope over the framing protocol
  Future<String> sendChatMessage({
    required String senderId,
    required String senderName,
    required String content,
  });

  /// Helper to send framed JSON over TCP: [4-byte length][JSON bytes]
  Future<void> sendEnvelope({required MessageEnvelope envelope});
}

class MessageEnvelope {
  final int version;
  final String msgId;
  final String senderId;
  final String senderName;
  final PlatformInt64 timestamp;
  final MessagePayload payload;

  const MessageEnvelope({
    required this.version,
    required this.msgId,
    required this.senderId,
    required this.senderName,
    required this.timestamp,
    required this.payload,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      msgId.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      timestamp.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageEnvelope &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          msgId == other.msgId &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          timestamp == other.timestamp &&
          payload == other.payload;
}

@freezed
sealed class MessagePayload with _$MessagePayload {
  const MessagePayload._();

  const factory MessagePayload.handshake({
    required String clientVersion,
    String? publicKey,
  }) = MessagePayload_Handshake;
  const factory MessagePayload.chatMessage({required String content}) =
      MessagePayload_ChatMessage;
  const factory MessagePayload.ack({
    required String targetMsgId,
    required String status,
  }) = MessagePayload_Ack;
  const factory MessagePayload.ping() = MessagePayload_Ping;
  const factory MessagePayload.pong() = MessagePayload_Pong;
}
