// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取当前时间的毫秒级 UTC 时间戳
Future<PlatformInt64> chronoNowTimestamp() =>
    RustLib.instance.api.crateApiUtilsChronoNowTimestamp();

/// 计算分块传输的 Block 数量
Future<int> calculateTotalChunks({
  required BigInt fileSize,
  required BigInt chunkSize,
}) => RustLib.instance.api.crateApiUtilsCalculateTotalChunks(
  fileSize: fileSize,
  chunkSize: chunkSize,
);
