// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../protocol.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Periodic scan tick called by Flutter timer
Future<void> scanAndFlush({required NetworkEngine engine}) =>
    RustLib.instance.api.crateApiDiscoveryBridgeScanAndFlush(engine: engine);
