// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models.dart';
import '../storage/traits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

// These functions are ignored because they are not marked as `pub`: `connections_map`, `setup_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TcpConnectionManager`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_or_connect`, `has_connection`, `remove_connection`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `insert_connection`, `new`, `set_engine`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerConnection>>
abstract class PeerConnection implements RustOpaqueInterface {
  String get remoteIp;

  set remoteIp(String remoteIp);

  Future<void> sendEnvelope({required MessageEnvelope envelope});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TcpConnectionManagerHandle>>
abstract class TcpConnectionManagerHandle implements RustOpaqueInterface {
  Future<ConnectionManagerHandle> asConnectionManager();

  Future<PeerConnectionHandle> getOrConnect({required String peerMac});

  Future<bool> hasConnection({required String peerMac});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TcpConnectionManagerHandle> newInstance({
    required String selfMac,
    required StorageRepositoryHandle storageHandle,
  }) => RustLib.instance.api
      .crateApiConnectionManagerTcpConnectionManagerHandleNew(
        selfMac: selfMac,
        storageHandle: storageHandle,
      );

  Future<void> removeConnection({required String peerMac});
}
