// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `get_or_connect`, `has_connection`, `remove_connection`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionManagerHandle>>
abstract class ConnectionManagerHandle implements RustOpaqueInterface {
  Future<PeerConnectionHandle> getOrConnect({required String peerMac});

  Future<bool> hasConnection({required String peerMac});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ConnectionManagerHandle> newInstance({
    required ArcConnectionManager inner,
  }) => RustLib.instance.api.crateApiConnectionTraitsConnectionManagerHandleNew(
    inner: inner,
  );

  Future<void> removeConnection({required String peerMac});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerConnectionHandle>>
abstract class PeerConnectionHandle implements RustOpaqueInterface {
  Future<String> remoteIp();

  Future<void> sendEnvelope({required MessageEnvelope envelope});
}
